# Wrangler configuration for password-protected file sharing
name = "protected-files"
main = "src/password-protect.js"
compatibility_date = "2024-09-02"
compatibility_flags = ["nodejs_compat"]

# Bind to R2 bucket for protected files
[[r2_buckets]]
binding = "PROTECTED_FILES"
bucket_name = "protected-files"

# KV namespace for storing password hashes
[[kv_namespaces]]
binding = "PASSWORDS"
id = "33eebef30dd54140a0485f4ae6dd9e9d"

# Custom domain (optional)
# route = "protected.yourdomain.com/*"