name = "secure-tunnel"
main = "src/hybrid-tunnel.js"
compatibility_date = "2024-01-01"

# KV namespace binding
[[kv_namespaces]]
binding = "TUNNEL_CONFIG"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_KV_NAMESPACE_ID"