# Wrangler Configuration Template for MacOS Dotfiles
# Copy this to wrangler.toml and fill in your actual IDs

name = "macos-dotfiles-secrets"
main = "src/index.js"
compatibility_date = "2024-09-02"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
[env.production]
workers_dev = false
# route = "your-domain.com/api/*"  # Uncomment and set your custom domain
# zone_id = "your_zone_id"         # Uncomment and set your zone ID

[env.development]
workers_dev = true

# Environment variables (non-secret)
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "info"

# KV namespaces for configuration storage (optional)
# [[kv_namespaces]]
# binding = "CONFIG_STORE"
# id = "your_kv_namespace_id"
# preview_id = "your_preview_kv_namespace_id"

# R2 bucket for file storage (optional)
# [[r2_buckets]]
# binding = "FILE_BUCKET"
# bucket_name = "your-r2-bucket-name"
# preview_bucket_name = "your-preview-bucket-name"

# D1 database for structured data (optional)
# [[d1_databases]]
# binding = "DB"
# database_name = "your-d1-database"
# database_id = "your_d1_database_id"

# Durable Objects migrations
[[migrations]]
tag = "v1"
new_classes = ["SecretManager"]

# Durable Objects for stateful operations
[[durable_objects.bindings]]
name = "SECRET_MANAGER"
class_name = "SecretManager"