# Wrangler configuration for public file server
name = "public-files-server"
main = "src/r2-public.js"
compatibility_date = "2024-09-02"
compatibility_flags = ["nodejs_compat"]

# Bind to your R2 bucket
[[r2_buckets]]
binding = "FILES_BUCKET"
bucket_name = "files"